import axios from "axios";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { useState } from "react";
import CardNews from "../components/CardNews";
import { useRouter } from "next/router";

export const getServerSideProps = async () => {
  const response = await axios.get(
    `https://inshorts.deta.dev/news?category=politics`
  );
  const news = response.data.data;
  return {
    props: {
      news: news,
    },
  };
};

const ServerSideRendering = ({ news }) => {
  const router = useRouter();

  const MoreDetails = (item) => {
    Router.push({
      pathname: `${item.author}`,
      query: {
        title: item.title,
        author: item.author,
        content: item.content,
        date: item.date,
        img: item.imageUrl,
        readMoreUrl: item.readMoreUrl,
      },
    });
  };

  return (
    <>
      <div>
        <Head>
          <title>News App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          {news.map((item, index) => (
            <CardNews
              key={index}
              author={item.author}
              img={item.imageUrl}
              title={item.title}
              date={item.date}
              onClick={() => ReadMore(item)}
            />
          ))}
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by News App{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
};

export default ServerSideRendering;
